// coagents-research-canvas/ui/src/app/layout.tsx

"use client";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "@copilotkit/react-ui/styles.css";
import "./globals.css";

// Import CopilotProvider and actions
import { CopilotProvider } from "@copilotkit/react-core";
import { ArxivSearchAction, WebSearchAction, RAGAction } from "@/lib/actions";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define actions array
const actions = [ArxivSearchAction, WebSearchAction, RAGAction];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CopilotProvider actions={actions}>
          {children}
        </CopilotProvider>
      </body>
    </html>
  );
}
