openai_api_key = "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"
pinecone_env = ""
pinecone_api_key = "b5503049-de06-497e-8245-19f509039452"